target:   test                # 対象のtexファイルの名前
tex_cmd:  platex -kanji=utf8  # .texをコンパイルするコマンド
bib_cmd:  pbibtex -kanji=utf8 # .bibをコンパイルするコマンド
dvi_cmd:  dvipdfmx            # .dviをコンパイルするコマンド
xbb_cmd:  extractbb           # .xbb (.bb) ファイルを生成するコマンド
open_cmd: open                # できたpdfを開くコマンド
images_dir_path: images       # 画像のあるフォルダ名
